language: node_js
node_js:
  - "lts/*"
sudo: false
cache: yarn
before_script:
  - npm install --global yarn nyc
script:
  - yarn lint
  - yarn build
  - yarn benchmark
  - yarn test-coverage
after_script:
  - npm install --global coveralls
  - nyc report --reporter=text-lcov | coveralls
