language: node_js
node_js:
  - "lts/*"
sudo: false
cache: yarn
before_script:
  - npm install --global yarn nyc
script:
  - yarn lint
  - yarn build
  - yarn test-coverage
  # - yarn benchmarks
after_script:
  - npm install --global codecov coveralls codacy-coverage
  - cat ./coverage/lcov.info | coveralls
  - cat ./coverage/lcov.info | codecov
  - cat ./coverage/lcov.info | codacy-coverage
