name: Benchmark

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  benchmark:
    name: Benchmark
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3.1.0

      - name: Install Dependencies
        run: yarn

      - name: Run Benchmark
        run: yarn benchmark2
